### PR TITLE
Add Kulpreet Singh, from libbitcoin institute.

### PR DESCRIPTION
**Pull request by kulpreet**

### CODE REVIEW

**Comment by modl21** [comment]
I don't see a donation option at the link you provided? (https://www.opdup.com/)

**Comment by kulpreet** [comment]
Not really looking for donation yet. By leaving a link to my website, I leave the option to drop in donation information there in future. Does that work?

**Comment by dennisreimann** [comment]
I'd say you can resubmit it once your donation option is set up. After all, this is a donations portal :)

**Comment by kulpreet** [comment]
> I'd say you can resubmit it once your donation option is set up. After all, this is a donations portal :)

Good point. Added a link to my github sponsors page as the `donate` property.

**Review by modl21 — APPROVED** [review]
ACK

**Pull request merged**
