### PR TITLE
Create saibato.json

### PR DESCRIPTION
**Pull request by Saibato**

### CODE REVIEW

**Comment by modl21** [comment]
Donation button should link to a page that hosts your donation address. Ideally it shouldn't reuse addresses for privacy reasons, consider btcpay server, but that is up to you.

**Comment by Saibato** [comment]
> Donation button should link to a page that hosts your donation address. Ideally it shouldn't reuse addresses for privacy reasons, consider btcpay server, but that is up to you.

hi, was anyway more a driveby i noticed and liked the site and what u do thing PR, I am not sure to link to a site since i want not have folks to have the impression that they should really sponsor me, although, if i would have utxos that are not linked to my identity that an avatar of me can use for online things like vpn,servers,paywalls  etc. that would be nice to have since my stack of old anon coins are less and less and staking sats can not cope the costs.

So thx for the comment ping, but i guess i might close this, if i can not skip provide a perm link. that cry's loud donate! ;-)  If u like, could i push a change to the site src that makes that possible?

**Comment by modl21** [comment]
What if you put the bitcoin donation address on your github page and then link to that?

Alternatively you could use the new donation account feature in hexa wallet to setup a non custodial donation page, see here: https://twitter.com/matt_odell/status/1314203484942557187

**Comment by Saibato** [comment]
thx hexa looks nice, at least u know now that i would not mind to get dust utxos from defacers dumped on me by coin selection, to make some return to sender with some nice shady extra fees package to them and by that those dusting efforts worthless, ;-)
Maybe its better for me to stay low profile, so i close this PR i now,

**Comment by Saibato** [comment]
hi, @modl21 reopened this, since Tor has a BTCPayserver Donation site. I linked to that, seams to be in line for what kind of things i like and stand for ,-)

**Pull request closed without merging**
