### PR TITLE
Create emzy.json

### PR DESCRIPTION
**Pull request by Emzy**

### CODE REVIEW

**Comment by modl21** [comment]
Currently we have limited this page to devs but will leave this PR open to see if anyone has strong opinions on merging?

**Comment by modl21** [comment]
Maybe we add a non-dev tag for this sort of thing?

**Comment by renepickhardt** [comment]
https://github.com/bitcoin/bitcoin/blob/3641ec1aacfe9a06d1e3f89875c0d0828639c4c2/src/chainparams.cpp#L128

Indicates that @Emzy runs Bitcoin dns seed servers which are distributed in Bitcoin core. If that is not critical and crucial infrastructure then I don't know!

Maybe reconsider @modl21?

**Comment by modl21** [comment]
Good point. ACK

**Pull request merged**
