### PR TITLE
Add vincenzopalazzo to donatees list 

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

### CODE REVIEW

**Comment by jsarenik** [comment]
There are two commits with the same subject containing the same typo. Please fix that @vincenzopalazzo  (squash and edit with `git rebase -i`).

**Comment by vincenzopalazzo** [comment]
Thanks, @jsarenik for the review, now the double commit should be fixed.

**Comment by jsarenik** [comment]
@vincenzopalazzo The commit subject still says "danation" instead of "donation".

**Comment by jsarenik** [comment]
@vincenzopalazzo One more nit. Once the commit is merged the "Proposed ...[long sentence ended with dot follows]" part of the subject does not make sense. It is also good to [check](https://github.com/dennisreimann/bitcoindevlist.com/commit/2f00a52) [previous](https://github.com/dennisreimann/bitcoindevlist.com/commit/9d85785) [commits](https://github.com/dennisreimann/bitcoindevlist.com/commit/5028f82) when people were adding themselves and stick to the culture of the repo. So please keep it simple:

```
Add vincenzopalazzo
```

PS: no dot in the end of line please, this is first line of a commit description, something like Subject in the email
PPS: "donatee" means [according to Wordnik](https://www.wordnik.com/words/donatee) "Someone who has received a donation or Someone who needs a donation."
PPPS: Adding @vincenzopalazzo (with `at`, referring to a github nickname) is considered spam in other projects, so maybe just think about it for a while and take it as part of culture. In this case it would be of course self-directed SPAM :)

Thank you @vincenzopalazzo for showing me all this, I am considering adding myself just to encourage anyone else who still hesitated to add themselves here :-)

**Review by jsarenik — CHANGES_REQUESTED** [review]
All the lines are OK (hopefully, did not check all the links/LN addresses), I am commenting only the commit message.

**Comment by vincenzopalazzo** [comment]
@jsarenik  you should add yourself to this list, you make a great contribution to bitcoin-related projects.

>PPPS: Adding @vincenzopalazzo (with at, referring to a github nickname) is considered spam in other projects, so maybe just think about it for a while and take it as part of culture. In this case it would be of course self-directed SPAM :)

I disagree with this, only because this is bad for accessibility, tools like GitHub highlights the GitHub name, and make life easier for people that have reading problems. Some cultures, need to be reviewed to give all the possibilities to have an easier life. But I'm just a coder, I care about the code accessibility, and for now, this change makes sense. Thanks :)

**Review by jsarenik — APPROVED** [review]
ACK 93296094564783d097e821dbce6f316074dc8f79

**Review by dennisreimann — APPROVED** [review]

**Pull request merged**
