### PR TITLE
Add practicalswift

### PR DESCRIPTION
**Pull request by practicalswift**
Add practicalswift :)

### CODE REVIEW

**Comment by dennisreimann** [comment]
ACK. The text is much longer than most of the other ones though, would you mind shortening it a bit?

**Comment by practicalswift** [comment]
@dennisreimann Thanks a lot for your quick review! I've now tried hard to shorten it while still giving readers the relevant information. I managed to shorten it by removing two sentences. Is it acceptable now? :)

**Comment by dennisreimann** [comment]
I don't want to be a gatekeeper here, compared to others it is still prerry long though.
We have no hard rules on anything here, but imho we should strive for some kind of consistency so that we don't get into lengthy debates and can prevent arguing. 

Chris Belcher's text is also pretty long and I think we should aim for a short description and putting details on the page the donation link points to.

Hope this makes sense, what do you thing @modl21?

text

**Comment by practicalswift** [comment]
@dennisreimann I think Chris' entry is fine (567 bytes): it is roughly the length of two tweets (560 bytes). As a donor I appreciate two tweets of context to be able to curate a short list of donatees without having to click them all :)

I'll trim down my entry so that it significantly smaller than Chris' entry and we should hopefully be ready to go. Will push soonish! :)

**Comment by practicalswift** [comment]
After some squeezing my description is now trimmed to less than two tweets of size, and roughly 2 % smaller than Chris' entry. Acceptable? :)

**Comment by dennisreimann** [comment]
Thanks!

**Pull request merged**
