### PR TITLE
add: Fitti

### PR DESCRIPTION
**Pull request by Fittiboy**
My main work, Bitcoin on Twitch, in action: https://twitter.com/Fittiboy/status/1422287674048720898

### CODE REVIEW

**Comment by Fittiboy** [comment]
I‘ve also contributed to lnurl (LUD-17):
https://github.com/fiatjaf/lnurl-rfc/blob/luds/17.md#lud-17-protocol-schemes-and-raw-non-bech32-encoded-urls

**Comment by dennisreimann** [comment]
This sounds like @arcbtc can easily provide an ACK here :)

And while we are at it: Ben, you might want to add yourself too!

**Comment by arcbtc** [comment]
Ack, Fitti is most excellent and should be added to everything.
I'll add myself if I can use my LNbits donation link?

**Comment by dennisreimann** [comment]
@arcbtc Yes, you can use any URL to point to a donation page of yours.

**Comment by arcbtc** [comment]
Oooo, then I would like to also be added 
I started 
LNbits 
LNPoS https://github.com/arcbtc/LNPoS

**Comment by arcbtc** [comment]
Oooo, then I would like to also be added as well please
I started:
LNbits https://github.com/lnbits/lnbits
LNPoS https://github.com/arcbtc/LNPoS
LNTrigger https://github.com/arcbtc/lntrigger
FOSSA https://github.com/arcbtc/The-Fossa
Muffin-Man https://github.com/arcbtc/The-Muffin-Man
Where39 https://github.com/arcbtc/where39
Nostr-Twitter https://github.com/arcbtc/nostr

Tip link: https://lnbits.com/paywall/GAqKguK5S8f6w5VNjS9DfK

**Comment by dennisreimann** [comment]
Can you open a PR with a JSON document like Fitti did?

**Comment by Fittiboy** [comment]
@arcbtc You can submit a PR like this one. All you need to do is put together a json file with all the information in it!

**Comment by arcbtc** [comment]
Got it! Will do. thanks!

**Pull request merged**
